### ISSUE TITLE
Birding

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/global-sprint-2016#54]
**[ Project Lead ]** @Akronix
**[ GitHub Repo ]** https://github.com/Akronix/birding
**[ Track ]** Tools: you are building a tool others can help you build
**[ Level ]** Beginner
**[ Timezone ]** CEST

### Description
This project aims to develop an intuitive, portable, extensible and easy to use web Application for tracking birds from GPS data.

***
## Want to Contribute?
Join us at the [Global Sprint June 2-3](https://www.mozillascience.org/global-sprint-2016). Leave a comment in this issue to let the project lead know you're interested in contributing during #mozsprint 2016!
***

## Note to the Project Lead
Congrats, @Akronix! This is your official project listing for the [Mozilla Science Global Sprint 2016](https://www.mozillascience.org/global-sprint-2016). To confirm your submission, please complete the following:

- [x] Provide a GitHub repository for work and discussion on your project
- [x] Confirm in a comment that at least one person will be available to review and answer questions on this project from 9-5 in their timezone on both June 2 & 3. Please specify timezone. :clock1:

#### Do you want to become a featured project? :tada:
Here are some exercises that will help your project be more inviting to new contributors. We hope you'll try to complete some of these as you prepare for #mozsprint.

If you complete *all* the exercises, your project will be eligible to be featured in our [collection of open source science projects](https://mozillascience.org/collaborate)! Once you've finished this list, contact @acabunoc to submit your project for review.

* [x] [README.md](http://mozillascience.github.io/working-open-workshop/writing_readme/):
* [x] [LICENSE](http://choosealicense.com/):
* [x] [CONTRIBUTING.md](http://mozillascience.github.io/working-open-workshop/contributing/):
* [ ] [Roadmap or an Issue Tracker (with tasks to complete)](http://mozillascience.github.io/working-open-workshop/roadmapping/):
* [x] [Data Reuse Plan](http://mozillascience.github.io/working-open-workshop/data_reuse/) (if applicable):
* [x] [Code of Conduct](http://mozillascience.github.io/working-open-workshop/code_of_conduct/):
* [ ] [Personas](http://mozillascience.github.io/working-open-workshop/personas_pathways/):

**Comment by Akronix** [comment]
Hi! I'm the project leader of [birding](https://github.com/Akronix/birding). @PedroLander is on the crew too.

We want to confirm that someone will be available on Thursday and Friday to review and answer questions. We cannot guarantee immediate answer on mornings since we are working, but we'll answer as soon as we have a break and we'll be pretty much available at evening from 19:00 ( UTC: 17:00) till night. Our timezone is CEST.

You can contact us either [via gitter](https://gitter.im/Akronix/birding), via mail (akronix5@gmail.com) or, **best options**: directly replying this thread or writing a new issue on the [github repo](https://github.com/Akronix/birding/issues).

We have no any code yet, but we do have an idea of what we need.
We're thinking to implement it in python using django framework.
